### ISSUE TITLE
Create Partner API

### ISSUE THREAD

**Issue by FlatBallFlyer** [agile-learning-institute/mentorHub-partner-api#1]
Draft swagger first once that is approved - 
- [ ] Setup node, express
  - Full directory structure
  - Rough in all Class and Methods (return true)
  - Hello-world routes for all endpoints - curl get "hello world" reply.
- [ ] Create API User Stories
- [ ] Create [Jest TDD tests](https://jestjs.io/docs/getting-started) for all classes
- [ ] finish Config endpoint
- [ ] finish Enums endpoint
- [ ] Finish People get endpoint
- [ ] Finish Partner post endpoint
- [ ] Finish Partner get endpoint
- [ ] Finish Partner get{id} endpoint
- [ ] Finish Partner patch{id} endpoint
- [ ] Finish Contact post endpoint
- [ ] Finish Contact delete endpoint
- [ ] Finish Health endpoint
- [ ] Build black box testing with [Postman](https://learning.postman.com/docs/getting-started/overview/)
- [ ] Update README

**Comment by modonnell0723** [comment]
I have made the final changes to Swagger, but not allowed to publish the branch? Suggestions?

**Comment by modonnell0723** [comment]
I have made recent commit on the issue-1 branch. Will you let me know if I am headed in the right direction? Created server and connected to MongoDB.

**Comment by modonnell0723** [comment]
Disregard last commit comment; the most recent commits are the ones I would like you to review.
